.\" Manpage for jadm.
.\" Contact jadm@dachev.info to correct errors or typos.
.TH man 8 "11 Mar 2014" "0.7" "jadm man page"
.SH NAME
jadm \- FreeBSD jail framework with vnet, zfs and /etc/jail.conf support
.SH DESCRIPTION
Jadm provide jail framework which use only FreeBDS native /etc/jail.conf file.
Jadm just pars /etc/jail.conf file also use FreeBSD integrated zfs functionality, bsdinstall for jail creations (also src) and freebsd jail tools.
Jadm create custom /etc/jail.conf file with initsetup() function (make a backup if /etc/jail.conf exist)
Jadm use zfs for jail envoirment also bridge+epair interfaces for vnet(vimage) network
.SH REQUIREMENTS
.TP
.B 'option vimage' 
in FreeBSD custom kernel
.TP
.B already exinsting zfs pool
.TP
.B already existing bridge interface with ip address
 (you can use multiple ip's which are used for jails gateways for different network)
.SH OPTIONS
.TP
.B initsetup
select existing bridge interface as default and jails home zfs (zpool should exist)
.TP
.B setup
change bridge interface (if you change it please change and jails gatways/ip via modify option) and default jail home zfs (jadm will rename all jails home path to new zfs home)
.TP
.B help
show jadm help information
.TP
.B about
show jadm version and license
.TP
.B exit or '!'
exit from jadm
.TP
.B create
Easy interactive way to create new jail
.br
 
.br
.B Jail Name:>
this name will be used also for jail zfs Jail
.br
 
.br
.B Hostname:>
jail hostname example: jail.local.lan
.br
 
.br
.B Jail ID:>
will be used also for jail epair inteface number (vnet / bridge interface conection)
.br
 
.br
.B Gateway number:>
show brige interfaces asignet ip addresses which are used for jail default gatway and jail network just select a number
.br
 
.br
.B Jail ZFS Quota (M)egabytes, (G)igabytes, (none) for unlimited:>
enter zfs quota for jail use none if quota is not needed example: 10G
.br
.TP
After all required data is entered jadm will show summarise config and will ask for confirmation (y/n) In this stage jadm will create zfs path for your jail if this zfs path already exist jadm will ask how to proceed
.br
.B (recreate)
will destroy zfs path and existing data and will create new one with same name
.br
 
.br
.B (use)
will use existing zfs path (jail environment) and will complete installation
.br
 
.br
.B install source:>
jadm will ask how to install new jail
.br
 
.br
.B (template)
use existing jail like a template - only jail name can be used
.TP
Any existing jail can be used like template. ZFS environment from existing jail will be copied in new jail, during this process jadm will create temporary file "jadm_temp_file" with original zfs content.
.br
 
.br
.B (bsd)
use bdsinstaller which is similiar to new freebsd instalation. During this process bsdinstaller will use internet to donwload FreeBSD pkg's
.br
 
.br
.B (src)
jadm will build jail environment from sources /usr/src. You can make new buildworld or you can use already builded
.br
.TP
After jail installation complete jadm will execute post install function with default settings for jail /etc/rc.conf and /etc/resolv.conf
.br
 
.br
.B /etc/jail.conf
.br
sendmail_enable="NONE"
.br
firewall_enable="YES"
.br
firewall_script="/etc/rc.firewall"
.br
firewall_type="OPEN"
.br
 
.br
.B /etc/resolv.conf
.br
nameserver 8.8.8.8
.TP
.B destroy
remove jail config from /etc/jail.conf and destroy jail zfs data (all jail data will be deleted)
.TP
.B remove
remove jail config from /etc/jail.conf but will keep jail zfs data which can be used for new jail
.TP
.B modify
easy modify existing jail settings (name, hostname, jid, gateway, ip addr and zfs quota)
.TP
.B listsnap
List jail zfs snapshots by jail name or ID
.TP
.B createsnap
Create jail zfs snapshot with special data/time number at the end
.TP
.B restoresnap
Select snapshot number from list which should be restored !!! If jail zfs will be restored from older snapshot all newer snapshots will be destroyed !!!
.TP
.B rmsnap
Select snapshot number from list which should be removed
.TP
.B start
Start Jail
.TP
if jail name content "tmeplate" jadm will skip it when "start all" is used
.TP
.B stop
Stop Jail
.TP
.B list
List Jais by name, hostname, ipaddress, gateway, active, inactive
.TP
.B local
.br
Jails local options
.br
For local option you can use all fine tunning jail options like 'mount.ftab' and etc. Local option apply only to jail. Local option should be set in this format 'option=val;' or jadm will not accept it.
.br
.B - List Jail local options
(usage: local list 'name/jid' )
.br
.B - Remove Jail local options
(usage: local rm 'name/jid' )
.br
.B - Add Jail local option
(usage: local add 'name/jid' 'option=val;')
.TP
.B global
.br
Jails global options
.br
For global option you can use all fine tunning jail options like 'mount.ftab' and etc. Global option apply only to all jails. Global option should be set in this format 'option=val;' or jadm will not accept it.
.br
.B - List Jails global options
(usage: global list )
.br
.B - Remove Jails global options
(usage: gloval rm )
.br
.B - Add Jails global option
(usage: global add 'option=val;')
.TP
.B shell
Enter in Jail (usage: shell 'jailname, jid or all')
.TP
.B gateways
List available Jail gateways on the system

.SH SEE ALSO
jail(8), jail.conf(5), zpool(8), zfs(8), ifconfig(8) and bridge(4)
.SH BUGS
If you find any bugs, or if you experience any crashes, please send report to jadm@dachev.info
.SH AUTHOR
Nikolay Georgiev Dachev (nikolay@dachev.info)
