#!/usr/bin/env python

from setuptools import setup, find_packages
setup(
    name = "jadm",
    version = "0.7",
    packages = find_packages(),
    scripts = ['jadm'],

    # Project uses reStructuredText, so ensure that the docutils get
    # installed or upgraded on the target machine
    install_requires = ['docutils>=0.3'],

    # metadata for upload to PyPI
    author = "Nikolay Georgiev Dachev",
    author_email = "jadm@dachev.info",
    description = "JADM is a easy FreeBSD 10 jail framework with /etc/jail.conf, vnet and zfs support ",
    license = "BSD 3-Clause",
    keywords = "jadm vnet zfs jail.conf",
    url = "https://github.com/NikolayDachev/jadm",   # project home page, if any

    # could also include long_description, download_url, classifiers, etc.
)
